### PR TITLE
Fix the stream method

### PR DESCRIPTION
**Pull request by mixmix**
fixes : https://github.com/flumedb/flumeview-reduce/issues/4

## Problem

`db[name].stream()` was behaving inconsistenly: 
- emits initialValue like `{ sum: 10, squareSum: 100 }`
- subsequent emmited values from just after a map e.g. `20`

## Changes

Given I can easily get the value `20` from creating a stream `db.stream()`, I have changed the code to consistently emit reduced state. I've wirtten test in case that sounds unclear.

I've updated the README to include:
- this behaviour
- a couple of unmentioned _hidden args_ that look useful

### CODE REVIEW

**Comment by dominictarr** [comment]
I think a better solution here would be a module that you use on client side to accept this stream and run the reduce on the mapped values there. For toy cases like this, where the reduce state is just a single number, then streaming the reduce is fine, but for most of the uses in ssb ecosystem it would send a lot of data!

**Comment by dominictarr** [comment]
okay, that was my answer without context. If my previous suggestion didn't make sense on it's own, please give more context. "explain what you are trying to do" [newly minted "good pull request" section in ssb-handbook!](https://github.com/ssbc/ssb-handbook/blob/master/contributing.md#explain-what-you-are-trying-to-do)

**Comment by dominictarr** [comment]
I mean, tell me about the thing you where trying to build with this just now that caused you to have this problem.

**Comment by mixmix** [comment]
I built some demo code and it didn't do what I thought the docs said.
I raised an issue trying to make an educated guess at the intended
behaviour, and it elicited response.

In the process I practiced writing tests and read the code even more
closely. I think the tests and should stay (these are a firm of
documentation) and the behaviour should revert to the original. The docs
will get a tweak to help a further person falling in a hole I did

**Comment by mixmix** [comment]
Nice language around types of pr.
I think i announced problem, but patch is much clearer.

**Comment by dominictarr** [comment]
> I think the tests and should stay (these are a firm of documentation) and the behaviour should revert to the original.

The tests currently test the incorrect behaviour so but would be happy to merge them if you change them stream reduce+map output.

I'm still figuring out what the guide should be. thread is here:
%SV7GH2wsKfYXCFzlCwLBtmr8Vb3VLV+ZCTqKIQtdmlw=.sha256

btw, it was @evbogue's intern proposal that made me decide we needed to formalize a bit (for training, etc)

**Comment by mixmix** [comment]
Updates @dominictarr : 
- revert code behaviour to original
- leaves tests
- adds a code example to README

NOTE: I think the example with `statistics` could be simpler. This forced me to read about that module, which was good/ bad? But more importantly, I don't think `statistics` reducer looks like it only sets initial state if `acc === null`, whereas `flumeview-reduce` will kick off with `undefined`... unless you manually set an inital state using `Reduce(1, reducer, map, null, initial)` mmmm    
Can solve that later

**Comment by dominictarr** [comment]
no it's `acc == null` (double equal). double equal to null is the same as `acc === null || acc === undefined`

there is often a tradeoff between a contrived example which may be simple, but so meaningless that it doesn't really illuminate _why_ you'd use it... and a real world example that is meaningful (i.e. you'd want to use it) but is too complicated that it obsecures what you are trying to show. I think maybe `statistics` is at a good balance point, but happy to hear suggestions of other examples. 

otherwise, merging!

**Comment by dominictarr** [comment]
merged into 1.3.12

**Comment by mixmix** [comment]
the code I wrote in the tests could be good.
It's like a simple slice of stats : { sum, squareSum } is collected.
Not too much code, but enough to see what's going where.

**Comment by mixmix** [comment]
aside - you have a pattern of saying "merged into 1.3.12" which I don't
have.
Is this something you'd like to include in a good PR guide ?  I haven't
ever used that info that you've posted, figured it was courtesy.... I guess
I'm assuming when things are merged they are generally published (mostly
the case for these smaller modules....  maybe not for bigger things like
Patchwork.

**Comment by dominictarr** [comment]
yes, I nearly always publish every merged pr. even if it was tiny. if it's a documentation fix, that still fixes the docs on npmjs.com if it was a patch or a feature, I figure the requestor wants to make use of that. I know sometimes I have a PR merged and then have to ask for it to be published... or check that it's been published.

yeah, patchwork has more work to do to cut a release, but if it's just npm pub I reckon publish every PR.

**Comment by dominictarr** [comment]
one exception: typo fixes, might just merge into master.

**Pull request merged**
